symbols:
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "BTCUSDT"
  - "BTCUSDT"
  - "BTCUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "BTCUSDT"
  - "BTCUSDT"
  - "BTCUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "BTCUSDT"
  - "BTCUSDT"
  - "BTCUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "BTCUSDT"
  - "BTCUSDT"
  - "BTCUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "BTCUSDT"
  - "BTCUSDT"
  - "BTCUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "BTCUSDT"
  - "BTCUSDT"
  - "BTCUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "BTCUSDT"
  - "BTCUSDT"
  - "BTCUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "BTCUSDT"
  - "BTCUSDT"
  - "BTCUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "BTCUSDT"
  - "BTCUSDT"
  - "BTCUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "BTCUSDT"
  - "BTCUSDT"
  - "BTCUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "BTCUSDT"
  - "BTCUSDT"
  - "BTCUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "BTCUSDT"
  - "BTCUSDT"
  - "BTCUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "BTCUSDT"
  - "BTCUSDT"
  - "BTCUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "BTCUSDT"
  - "BTCUSDT"
  - "BTCUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "EOSUSDT"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "LTCBTC"
  - "BTCUSDT"
  - "BTCUSDT"
max_workers: 161